name: Chart Version Test

on:
  pull_request:
    branches:
      - main

jobs:
  chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get old chart version
        id: old_version
        shell: bash
        run: |
          old_version=$(grep version\: charts/to-monitor/Chart.yaml | awk -F ' ' '{print $2}')
          echo "old_version=$old_version" >> $GITHUB_OUTPUT

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Get new chart version and compare
        id: new_version
        shell: bash
        run: |
          new_version=$(grep version\: charts/to-monitor/Chart.yaml | awk -F ' ' '{print $2}')
          old_version=${{ steps.old_version.outputs.old_version }}
          echo "new_version = $new_version"
          echo "old_version = $old_version"
          
          if [[ "$new_version" == "$old_version" ]]; then
            echo "New and old Chart versions are equal. Please increase the Chart version"
            exit 1
          fi
          
          new_version=(${new_version//./ })
          old_version=(${old_version//./ })
          
          for i in $(seq 0 2); do
            case "$i" in
              0)
              version="Major"
              ;;
          
              1)
              version="Minor"
              ;;
          
              *)
              version="Patch"
              ;;
            esac
          
            if [[ "${new_version[$i]}" -gt "${old_version[$i]}" ]]; then
              echo "$version version is greater than previous one"
              echo "Version is OK"
              break
            elif [[ "${new_version[$i]}" -eq "${old_version[$i]}" ]]; then
              echo "$version version is equal to previous one. Keep checking..."
            else
              echo "$version version is lower than previous one"
              echo "Version is not OK. Please increase the Chart version"
              exit 1
            fi
          done
          
          exit 0
