name: Helm Template Test

on:
  pull_request:
    branches:
      - main

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render helm chart
        shell: bash
        run: |
          helm template to-monitor charts/to-monitor
